// Re-export shared types for convenience
export type {
  User,
  UserSummary,
  Tenant,
  TenantSummary,
  Ticket,
  TicketListItem,
  TicketReply,
  Attachment,
  AuditEntry,
  AssignmentRule,
  RuleCondition,
  AgentGroup,
  AgentGroupSummary,
  SLAPolicy,
  CannedResponse,
  KBArticle,
  KBArticleListItem,
  KBSearchResult,
  KBCategory,
  CSATResponse,
  HeartbeatViewer,
  PaginatedResponse,
  ErrorResponse,
} from '@busybirdies/shared';
